version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ${APP_NAME}-be
    restart: always
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: ${APP_NAME}-fe
    restart: always
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx-${ENV}
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - default
    restart: always

networks:
  default:
    name: ${APP_NAME}-${ENV}-net
    driver: bridge